version: "3"

tasks:


  set_weights:
    cmds:
      - JUST_ONCE=true docker compose --env-file .vali.env -f docker-compose.yml run -e LOCALHOST=false --entrypoint "python src/set_weights/calculate_and_schedule_weights.py" weight_setter

  show_stats:
    cmds:
      - docker compose --env-file .vali.env -f docker-compose.yml run -e LOCALHOST=false --entrypoint "python src/collect_statistics.py" control_node

  control_node_dev:
    cmds:
      - LOCALHOST=true ENV_FILE=.vali.env python -m validator.control_node.src.main

  query_node_dev:
    cmds:
      - LOCALHOST=true ENV_FILE=.vali.env python -m validator.query_node.src.main

  entry_node_dev:
    cmds:
      - LOCALHOST=true uvicorn validator.entry_node.src.server:app --reload --host 0.0.0.0 --port 8090 --env-file .vali.env

  weight_setter_dev:
    cmds:
      - LOCALHOST=true ENV_FILE=.vali.env python -m validator.control_node.src.set_weights.calculate_and_schedule_weights

  m1_dev:
    cmds:
      - ENV=DEV uvicorn miner.server:app --reload --host 0.0.0.0 --port 7999 --env-file .1.env --log-level debug

  m2_dev:
    cmds:
      - ENV=DEV uvicorn miner.server:app --reload --host 0.0.0.0 --port 4002 --env-file .2.env --log-level debug


  dev_setup:
    cmds:
      - docker compose --env-file .vali.env -f docker-compose.yml -f docker-compose.dev.yml up -d --build

  validator:
    cmds:
      - ENV_FILE=.vali.env uvicorn --factory validator.asgi:factory --host 0.0.0.0 --port 9001 --env-file .vali.env

  miner:
    cmds:
      - docker compose --env-file .vali.env -f docker-compose.yml -f docker-compose.dev.yml up -d --build
