version: "3"

tasks:

  miner:
    cmds:
      - ENV=DEV uvicorn miner.server:app --reload --host 0.0.0.0 --port 7999 --env-file .1.env --log-level debug

  dev_setup:
    cmds:
      - docker compose --env-file .vali.env -f docker-compose.yml -f docker-compose.dev.yml up -d --build

  validator:
    cmds:
      - ENV_FILE=.vali.env uvicorn --factory validator.asgi:factory --host 0.0.0.0 --port 9001 --env-file .vali.env

