name: G.O.D
on:
  pull_request:
  push:
    tags:
      - "dev"
      - "staging"
      - "prod"

jobs:
  lint:
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10"]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]

    - name: Run linting
      run: ruff check G.O.D

  test:
    needs: [lint]
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        python-version: ["3.10"]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .[dev]

    - name: Install DBMate
      run: |
        wget https://github.com/amacneil/dbmate/releases/download/v2.12.0/dbmate-linux-amd64 -O ./dbmate
        chmod +x ./dbmate

    - name: Run tests
      run: |
        PATH=$(pwd):$PATH pytest -vv -xs tests/